# Generated by Django 4.2.16 on 2024-10-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorey',
            new_name='Category',
        ),
    ]
